language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t julianmateu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianmateu/docker-react yarn test --env=jsdom --ci --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: $S3_BUCKET
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
