language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t julianmateu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianmateu/docker-react yarn test --env=jsdom --ci --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-732712393157"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
