language: generic 

services:
  - docker

before_install:
  - docker build -t julianmateu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianmateu/docker-react yarn test -- --coverage
