name: Deploy Node app on AWS Elastic Beanstalk

env:
  APP_NAME: docker-react
  ENV_NAME: Dockerreact
  S3_BUCKET: elasticbeanstalk-us-east-2-732712393157
  AWS_REGION: us-east-2
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

on:
  push:
    branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.APP_NAME }}
        environment_name: ${{ env.ENV_NAME }}
        version_label: 12345
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip
